# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Charset
version:      0.8
version_from: lib/MARC/Charset.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Test::More:                    0
    Unicode::Normalize:            0
    XML::SAX:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
