---
abstract: 'convert MARC-8 encoded strings to UTF-8'
author:
  - 'Ed Summers <ehs@pobox.com>'
  - 'Galen Charlton <gmcharlt@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-Charset
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  Test::More: 0
  Unicode::Normalize: 0
  XML::SAX: 0
version: 1.34
