--- #YAML:1.0
name:               MARC-Charset
version:            1.3
abstract:           convert MARC-8 encoded strings to UTF-8
author:
    - Ed Summers <ehs@pobox.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:     0
    Test::More:          0
    Unicode::Normalize:  0
    XML::SAX:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
